apiVersion: v1
kind: Pod
metadata:
  name: kubia-gpu
  labels:
    creation_method: manual
    env: prod
spec:
  nodeSelector:
    gpu: "true"
  containers:
    - image: michaellundquist/kubia
    name: kubia
    ports:
    - containerPort: 8080
    protocol: TCP
