apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: batch-job-every-five-minutes
spec:
  schedule: "0,5,10,15,20,25,30,35,40,45,50,55 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: periodic-batch-job
        spec:
          restartPolicy: OnFailure
          containers:
          - name: main
            image: luksa/batch-job