apiVersion: v1
kind: ReplicationController
metadata:
  name: kubia
  annotations:
    description: "Ch 5.5.2 kubia-rc-readinessprobe.yaml"
spec:
  replicas: 3
  selector:
    app: kubia
  template:
    metadata:
      labels:
        app: kubia
    spec:
      containers:
      - name: kubia
        image: michaellundquist/kubia
        readinessProbe:
          exec:
            command:
            - ls
            - /var/ready
        ports:
        - containerPort: 8080
          name: http